@extends('layouts.app')
@section('title', 'Epreuve 10 : Questions generales & justifications projet')

@php
    $config = [
        'qcm_key' => 'fega-10',
        'title' => 'Epreuve 10 : Questions generales & justifications',
        'subtitle' => '18 questions . Soutenance . Justifier vos choix, modules, ameliorations, roles',
        'badge' => 'Gen',
        'color' => '#8B3D1A',
        'description' => 'Tous les "pourquoi" du projet : nom FeGArtisan, modules principaux, ameliorations futures, difference Admin/Super Admin, ce qu\'on a appris.',
        'is_exam' => false,
    ];

    $chapters = [
        ['title' => 'Justifications et contexte projet', 'num' => 1, 'lesson' => '
            <p>Le jury cherche surtout a comprendre vos <strong>choix</strong> (decisions techniques et fonctionnelles). Etre capable de <em>defendre</em> chaque decision (justifier rationnellement le pourquoi) est plus important que connaitre par coeur les details d\'implementation.</p>
            <p>Cette epreuve couvre les <em>questions generales</em> les plus probables : origine du nom FeGArtisan, objectif principal, modules du systeme, differenciation par rapport aux concurrents, identification des cibles, distinction entre les roles (utilisateur / administrateur / super administrateur), apprentissages personnels, methodologie de gestion de projet, perspective <em>startup</em> (entreprise innovante en croissance rapide).</p>
            <div class="tip">Conseil de soutenance : meme une reponse simple mais <strong>claire</strong> vaut mieux qu\'un discours complique appris par coeur. L\'examinateur cherche votre <em>maitrise</em> du projet, pas votre memoire.</div>
        '],
    ];

    $allQuestions = [
        ['chapter'=>0, 'question'=>"Pourquoi le nom FeGArtisan ?", 'options'=>['Aleatoire', 'Contraction qui rappelle <em>artisanat</em> + initiales personnelles des fondatrices. Le nom est court, prononcable en francais, et evoque immediatement le domaine', 'Marque deposee', 'Aucune raison'], 'answer'=>1, 'explanation'=>"Le nom combine une initiale de chaque fondatrice + <em>Artisan</em>. Court (10 lettres), prononcable, evoque le domaine. Le casque de chantier du logo renforce le visuel."],
        ['chapter'=>0, 'question'=>"Quel est l'objectif principal du projet ?", 'options'=>['Vendre de l\'artisanat en ligne', 'Mettre en relation rapide, efficace et securisee artisans et clients au Benin via une app mobile', 'Former les artisans au digital', 'Cartographier les artisans'], 'answer'=>1, 'explanation'=>"Pas un marketplace produit. C'est une plateforme de <strong>mise en relation</strong> (matchmaking) entre artisans (services) et clients."],
        ['chapter'=>0, 'question'=>"Quels sont les modules principaux du systeme ?", 'options'=>['1 seul', '5 modules : Auth/inscription, Recherche/profils, Publications/feed, Messagerie, Admin/moderation', 'Trop pour citer', 'Backend seul'], 'answer'=>1, 'explanation'=>"5 modules principaux : (1) <strong>Auth</strong> (inscription 2 etapes artisan + email verify) ; (2) <strong>Recherche</strong> + fiche artisan ; (3) <strong>Publications</strong> + feed ; (4) <strong>Messagerie</strong> + reactions + notifs ; (5) <strong>Admin</strong> (moderation + corbeille)."],
        ['chapter'=>0, 'question'=>"Quelle est la difference entre votre solution et les concurrents ?", 'options'=>['Aucune', '(1) UX mobile-first 100% francophone Benin ; (2) gratuit pour clients ET artisans ; (3) validation manuelle artisan par admin = confiance ; (4) pas que devis : feed + reviews + chat', 'On copie WhatsApp', 'On est moins cher'], 'answer'=>1, 'explanation'=>"4 differenciateurs : mobile-first francophone ; gratuit ; validation manuelle artisan (confiance) ; experience complete (pas seulement devis : feed social + reviews + chat)."],
        ['chapter'=>0, 'question'=>"Qui sont les utilisateurs cibles principaux ?", 'options'=>['Tout le monde', '3 cibles : (1) clients particuliers/entreprises cherchant un artisan ; (2) artisans (maconniers, couturiers, electriciens, plombiers, menuisiers, coiffeurs...) ; (3) admins moderateurs', 'Etudiants HECM', 'Diaspora'], 'answer'=>1, 'explanation'=>"3 cibles : Clients (B2C+B2B), Artisans tous metiers manuels, Admins (super admin + admins simples). Le super admin peut gerer les autres admins."],
        ['chapter'=>0, 'question'=>"Difference entre Admin et Super Admin ?", 'options'=>['Aucune', 'Admin : moderation contenus, validation artisans, gestion catalogue. Super Admin : tout cela + gestion des autres admins (creation, suspension, droits)', 'Salaire', 'Acces base SSH'], 'answer'=>1, 'explanation'=>"<strong>Admin</strong> : moderation, validation, catalogue. <strong>Super Admin</strong> : tout cela + <strong>gestion des autres admins</strong> via middleware <code>admin.manage</code> (colonne <code>can_manage_admins=true</code>)."],
        ['chapter'=>0, 'question'=>"Pourquoi avoir cree un role Super Admin distinct ?", 'options'=>['Hierarchie', 'Separation des responsabilites : un admin metier (moderation) ne doit pas pouvoir creer/supprimer d\'autres admins. Principe du moindre privilege', 'Caprice', 'Marketing'], 'answer'=>1, 'explanation'=>"<strong>Principe du moindre privilege</strong> : un admin metier (qui modere les pubs) ne devrait pas creer d'autres admins ni les supprimer. C'est une action super-admin reservee."],
        ['chapter'=>0, 'question'=>"Quels besoins ont ete identifies avant le developpement ?", 'options'=>['Aucun', 'Sondage de 71 repondants (50 clients + 21 artisans) realise du 5 au 7 mai 2026 : 72% des clients interesses, 66.7% des artisans, manque de visibilite #1 pour les artisans (95.2%)', 'Intuition', 'Etude marche payante'], 'answer'=>1, 'explanation'=>"<strong>Sondage 71 personnes</strong> (5-7 mai 2026). Resultats : 72% clients interesses, 66.7% artisans, 95.2% des artisans citent le manque de visibilite comme obstacle #1."],
        ['chapter'=>0, 'question'=>"Quelle a ete la difficulte technique majeure ?", 'options'=>['Aucune', 'La messagerie temps reel sur Hostinger mutualise qui ne permet pas les WebSockets. Resolu via polling 3s + FCM', 'L\'authentification', 'Le design'], 'answer'=>1, 'explanation'=>"Mise en oeuvre du <strong>temps reel</strong> sans WebSockets (contrainte Hostinger). Solution : <strong>polling 3s</strong> en chat ouvert + <strong>FCM</strong> en arriere-plan."],
        ['chapter'=>0, 'question'=>"Quelles ameliorations futures sont prevues ?", 'options'=>['Aucune', 'App iOS native, paiement in-app KKiaPay/FedaPay, recommandation IA, notation verifiee, geolocalisation GPS + tri distance, mode offline limite, WebSockets Reverb si budget VPS', 'Aucune idee', 'Recommencer'], 'answer'=>1, 'explanation'=>"Cite dans la conclusion du memoire : iOS, KKiaPay/FedaPay, IA recommandation, notations verifiees, GPS + tri distance, offline V2, et migration Reverb si VPS budget."],
        ['chapter'=>0, 'question'=>"Que peut faire un client (utilisateur final) ?", 'options'=>['Rien', 'Chercher un artisan par metier/ville, consulter profils, ajouter favoris, envoyer message, laisser avis, liker publications, signaler contenus', 'Tout', 'Que lire'], 'answer'=>1, 'explanation'=>"Client : recherche + filtres, fiche artisan, favoris, messagerie, avis, like publications, signalements."],
        ['chapter'=>0, 'question'=>"Comment un artisan cree-t-il son compte ?", 'options'=>['1 etape', '2 etapes : (1) infos de base + token immediate ; (2) upload justificatif (PDF/JPG/PNG max 5 Mo) + categorie. Puis attente validation admin + email verify', 'Auto cree', 'Demande SMS'], 'answer'=>1, 'explanation'=>"<strong>2 etapes</strong> : etape 1 publique (infos + token), etape 2 authentifiee (justificatif diplome/certificat/preuve_experience + categorie). Puis admin valide => mail signe email/verify."],
        ['chapter'=>0, 'question'=>"Comment contacter un artisan depuis l'app ?", 'options'=>['Appel direct', 'Bouton Contacter sur la fiche artisan => POST /api/conversations (cree ou recupere la conversation) => ouverture du ChatScreen avec polling 3s', 'Email', 'SMS payant'], 'answer'=>1, 'explanation'=>"Sur la fiche artisan : bouton Contacter => <code>conversationsRepository.startOrGet(artisanId)</code> => POST /api/conversations => navigation vers <code>/chat/{conversationId}</code>."],
        ['chapter'=>0, 'question'=>"Qu'avez-vous appris grace a ce projet ?", 'options'=>['Rien', 'Stack complet : Flutter/Dart, Laravel/Eloquent, integration Firebase, deploiement Hostinger + CI/CD GitHub Actions, gestion projet IT, enquete terrain, comprendre la digitalisation du secteur informel ouest-africain', 'Juste coder', 'Comment dormir tard'], 'answer'=>1, 'explanation'=>"Apprentissages cites dans le memoire : Flutter/Dart, Laravel MVC + Eloquent, Firebase FCM, deploiement Hostinger + CI/CD, gestion projet, enquete terrain, comprehension enjeux digitalisation Afrique."],
        ['chapter'=>0, 'question'=>"Quelle partie a ete la plus difficile et pourquoi ?", 'options'=>['Aucune', 'La communication temps reel (polling + lifecycle Flutter + FCM), l\'optimisation pour les appareils Android d\'entree de gamme (Samsung A03, Tecno, Infinix), et l\'adaptation responsive sur differentes tailles d\'ecran', 'Le login', 'Le footer'], 'answer'=>1, 'explanation'=>"3 difficultes citees : (1) <strong>temps reel</strong> + lifecycle Flutter ; (2) <strong>perfs sur entree de gamme</strong> ; (3) <strong>responsive</strong> sur differentes tailles d'ecran. Ces 3 problemes ont ete tous resolus."],
        ['chapter'=>0, 'question'=>"Si vous recommenciez le projet, que changeriez-vous ?", 'options'=>['Rien', 'Plus de tests automatises (Pest backend, flutter_test integration) des le debut, et un audit UX usability test avec 5 vrais utilisateurs Beninois avant le code', 'Tout', 'Equipe plus grande'], 'answer'=>1, 'explanation'=>"Reponse honnete et concrete : (1) <strong>tests automatises Pest + flutter_test</strong> des le J1 ; (2) <strong>tests utilisateur usability</strong> (5 personnes ciblees) avant le dev pour valider les hypotheses UX."],
        ['chapter'=>0, 'question'=>"Ce projet peut-il devenir une vraie startup ?", 'options'=>['Non', 'Oui : sondage valide (70.4%), MVP fonctionnel, modele economique possible (commission par mise en relation, abonnement Pro artisans, sponsoring), march local sous-digitalise', 'Trop tot', 'Pas rentable'], 'answer'=>1, 'explanation'=>"Potentiel reel : besoin valide (sondage 70.4%), MVP livre, modele eco possible (commission ou abonnement artisan Pro), marche beninois sous-digitalise. Concurrence faible localement."],
        ['chapter'=>0, 'question'=>"Quelle a ete votre methodologie de gestion de projet ?", 'options'=>['Aucune', 'Methode iterative inspiree d\'Agile : (1) sondage besoins ; (2) UML conception ; (3) developpement par feature ; (4) tests ; (5) deploiement progressif. 5 phases sur ~11 semaines selon le planning previsionnel', 'V-cycle strict', 'Aucune doc'], 'answer'=>1, 'explanation'=>"Methodologie iterative en 5 phases : Analyse (1s) + Conception (2s) + Developpement (5s) + Tests (2s) + Deploiement (1s). Total <strong>~11 semaines</strong> selon le tableau planning previsionnel du memoire."],
    ];
@endphp

@section('styles')
    @include('qcm._styles', ['config' => $config])
@endsection

@section('content')
    @include('qcm._engine', ['config' => $config, 'chapters' => $chapters, 'allQuestions' => $allQuestions])
@endsection
