@extends('layouts.app')
@section('title', 'Epreuve 9 : Questions pieges & scalabilite')

@php
    $config = [
        'qcm_key' => 'fega-9',
        'title' => 'Epreuve 9 : Questions pieges & scalabilite',
        'subtitle' => '16 questions . Soutenance . Performance, scalabilite, choix technos defendus',
        'badge' => 'Pieges',
        'color' => '#C94A3A',
        'description' => 'Les questions <em>pieges</em> du jury : et si 10 000 users en meme temps ? Si la BDD tombe ? Pourquoi Laravel et pas Node.js ? Quels sont les points faibles ?',
        'is_exam' => false,
    ];

    $chapters = [
        ['title' => 'Pieges classiques de soutenance', 'num' => 1, 'lesson' => '
            <p>Le jury teste si vous comprenez les <strong>limites</strong> de votre <em>stack</em> (ensemble des technologies utilisees : Laravel + Flutter + TiDB + FCM + Hostinger) et si vous savez argumenter vos choix techniques.</p>
            <p><strong>Regle d\'or :</strong> ne jamais affirmer que "ma solution est parfaite". Il faut au contraire <em>reconnaitre les limites</em> (faiblesses connues) et <em>expliquer pourquoi le compromis est acceptable</em> dans le contexte du projet (budget, hebergement, calendrier).</p>
            <p>Cette epreuve aborde la <em>scalabilite</em> (capacite a monter en charge avec plus d\'utilisateurs), la <em>resilience</em> (comportement en cas de panne), les choix de framework (pourquoi Laravel et pas Node.js / Django / Spring Boot), les points faibles connus et les pistes d\'optimisation.</p>
        '],
    ];

    $allQuestions = [
        ['chapter'=>0, 'question'=>"Si 10 000 utilisateurs se connectent en meme temps, que se passe-t-il ?", 'options'=>['Tout marche', 'Hostinger shared sature vite (256 Mo PHP-FPM). Il faut migrer sur Hostinger VPS ou Cloud, et passer Redis pour sessions/cache, plus eventuellement un load balancer', 'Crash sans recours', 'Aucun probleme grace a TiDB'], 'answer'=>1, 'explanation'=>"Hostinger mutualise <strong>sature</strong> aux pics de charge. Plan de scaling : VPS dedie => Redis pour sessions/cache => CDN pour les medias => load balancer. TiDB Cloud est deja scalable horizontalement, ce n'est pas le goulot."],
        ['chapter'=>0, 'question'=>"Que se passe-t-il si la base de donnees TiDB tombe ?", 'options'=>['L\'app continue', 'Erreurs 500 immediates partout. TiDB Cloud a un SLA 99.99% multi-AZ donc rare. Mitigation : page d\'erreur custom + retry + monitoring + alertes', 'Aucun impact', 'Failover auto vers SQLite'], 'answer'=>1, 'explanation'=>"TiDB tombe = <strong>erreurs 500</strong> immediates. TiDB Cloud Serverless est multi-AZ avec SLA eleve, panne tres rare. Mitigation = pages d'erreur claires + alertes + plan de bascule."],
        ['chapter'=>0, 'question'=>"Pourquoi Laravel et pas Node.js/Express ?", 'options'=>['Mode', 'Maturite du framework (auth, validation, ORM Eloquent, queues integres), syntaxe MVC claire pour soutenance, hosting PHP omnipresent en Afrique (cPanel), notre formation est PHP', 'Plus rapide', 'Aucune'], 'answer'=>1, 'explanation'=>"<strong>4 raisons</strong> : (1) maturite (Sanctum, Eloquent, validation, queues integres) ; (2) MVC clair pour la soutenance ; (3) hosting PHP partout en Afrique (cPanel) ; (4) cours HECM PHP-centric."],
        ['chapter'=>0, 'question'=>"Pourquoi pas Django (Python) ou Spring Boot (Java) ?", 'options'=>['Trop dur', 'Django : ecosysteme moins fourni hosting Afrique. Spring Boot : verbose + JVM lourde + cher a heberger. Laravel est le sweet spot performance/cout/familiarite', 'Trop cher', 'Pas open source'], 'answer'=>1, 'explanation'=>"Django excellent mais hosting Python partagee rare en Afrique. Spring Boot verbose + JVM tres lourde (RAM cher). Laravel = sweet spot performance/cout/familiarite locale."],
        ['chapter'=>0, 'question'=>"Pourquoi NE PAS avoir utilise Firebase comme backend complet ?", 'options'=>['Pas connu', 'Vendor lock-in Google, couts qui explosent passe le free tier, regles de securite limitees pour notre logique metier complexe (validation artisan, dossiers, etc.). On utilise Firebase UNIQUEMENT pour FCM (gratuit, fait son job)', 'Trop simple', 'Pas adapte mobile'], 'answer'=>1, 'explanation'=>"<strong>Vendor lock-in</strong> + <strong>couts</strong> apres free tier + <strong>regles Firestore limitees</strong> pour notre metier (workflow validation artisan, polymorphisme reports, etc.). Firebase n'est pas adapte au backend, on l'utilise uniquement pour FCM (cas d'usage simple, gratuit, fiable)."],
        ['chapter'=>0, 'question'=>"Quels sont les points faibles connus de votre application ?", 'options'=>['Aucun', 'Polling vs WebSockets (latence 3s en chat), pas de cache CDN sur les medias, dependance a Hostinger shared (pas de queue workers), pas encore d\'app iOS publiee', 'Tout est faible', 'Secret'], 'answer'=>1, 'explanation'=>"Honnete : (1) polling 3s vs WebSockets (mais necessaire pour Hostinger) ; (2) pas de CDN sur les medias ; (3) listeners synchrones obligatoires ; (4) iOS non publie. Reconnaitre les limites = maturite technique."],
        ['chapter'=>0, 'question'=>"Le systeme est-il scalable verticalement et horizontalement ?", 'options'=>['Non, monolithe rigide', 'Verticalement OK : changer Hostinger shared pour VPS / Cloud. Horizontalement : le backend Laravel est stateless (Sanctum tokens, pas de session serveur pour l\'API) => multi-instances possibles avec un load balancer. TiDB est deja horizontalement scalable', 'Seulement vertical', 'Difficile'], 'answer'=>1, 'explanation'=>"Backend stateless via Sanctum = <strong>multi-instances possibles</strong>. TiDB Cloud distribute. Vertical : changer le plan Hostinger. Horizontal : load balancer + N instances Laravel."],
        ['chapter'=>0, 'question'=>"Comment ameliorer les performances en production ?", 'options'=>['Aucun moyen', 'php artisan config:cache + route:cache + view:cache + opcache PHP + Redis cache/sessions + CDN media (Cloudflare gratuit) + image WebP + lazy loading', 'Changer Laravel', 'Aucune'], 'answer'=>1, 'explanation'=>"Liste : (1) caches Laravel <code>config/route/view:cache</code> ; (2) <strong>OPcache PHP</strong> ; (3) Redis cache/sessions ; (4) CDN Cloudflare (gratuit) ; (5) WebP + lazy loading."],
        ['chapter'=>0, 'question'=>"Comment ameliorer la latence du polling 3s pour les messages ?", 'options'=>['Reduire a 100ms', 'Migrer Reverb sur un VPS dedie quand le budget le permet, OU long-polling (la requete reste ouverte jusqu\'a 30s)', 'Acheter Firebase Premium', 'Impossible'], 'answer'=>1, 'explanation'=>"Solutions : (1) <strong>Laravel Reverb</strong> sur VPS pour vrai WebSocket ; (2) <strong>long-polling</strong> (la requete reste ouverte cote serveur jusqu\'a un nouveau message ou timeout 30s) ; (3) garder polling court mais l\'allonger en background."],
        ['chapter'=>0, 'question'=>"Comment gerez-vous les notifications temps reel hors-app ?", 'options'=>['Pas du tout', 'Firebase Cloud Messaging (FCM) gratuit. Push directement vers le device meme app fermee. Latence ~1s', 'WebSocket', 'SMS'], 'answer'=>1, 'explanation'=>"<strong>FCM</strong> gratuit, latence ~1s, fonctionne meme app fermee. Combine au polling 3s pour le foreground = couverture complete sans cout."],
        ['chapter'=>0, 'question'=>"Que faites-vous des photos uploadees par les artisans (10 Mo+) ?", 'options'=>['On accepte tout', 'Cote Flutter : compression flutter_image_compress avant upload (gain ~70%). Cote Laravel : validation type/taille (max 5 Mo apres compression)', 'On rejette', 'On stocke en base64 DB'], 'answer'=>1, 'explanation'=>"Compression cote client avant upload (<code>flutter_image_compress</code>, <code>video_compress</code>) economise bande passante critique au Benin. Validation Laravel : type MIME + taille max."],
        ['chapter'=>0, 'question'=>"Si TiDB Cloud passe en mode paying, quel est le plan B ?", 'options'=>['Rien', 'Migration vers MySQL classique (DigitalOcean Managed DB ~15$/mois, Hetzner ~5$). Le code Eloquent est portable, on change juste les credentials .env', 'Tout refaire', 'Ferme la boite'], 'answer'=>1, 'explanation'=>"Eloquent est <strong>portable</strong>. Switcher TiDB =&gt; MySQL Managed (DigitalOcean, AWS RDS, Hetzner) ne demande que les credentials. Migrations Laravel rejouables ailleurs."],
        ['chapter'=>0, 'question'=>"Le polling consomme la batterie. Comment l'optimiser ?", 'options'=>['Rien faire', 'Pause sur AppLifecycleState.paused (deja fait), polling rapide (3s) uniquement quand chat ouvert, polling lent (60s) pour la liste conversations, FCM pour le reste', 'Batterie infinie', 'Polling 1s'], 'answer'=>1, 'explanation'=>"Strategie en 3 etages : <strong>3s</strong> chat ouvert (utile) ; <strong>60s</strong> liste conversations (acceptable) ; <strong>FCM</strong> hors-app (zero batterie consomme par l'app)."],
        ['chapter'=>0, 'question'=>"Comment monitorer les performances en production ?", 'options'=>['Rien', 'Middleware LogRequestDuration => storage/logs/performance-YYYY-MM-DD.log. Dump SQL si >10 queries. Alerte sur N+1 (>30). Plus tard : Laravel Telescope ou Sentry', 'Google Analytics', 'Aucun'], 'answer'=>1, 'explanation'=>"<code>LogRequestDuration</code> logge temps + nb queries par requete. Dump SQL detaille si &gt;10 queries. Alerte si N+1 (&gt;30). Pour aller plus loin : <strong>Sentry</strong> (gratuit jusqu'a 5k events/mois) ou <strong>Laravel Telescope</strong>."],
        ['chapter'=>0, 'question'=>"L'app Flutter telecharge-t-elle de gros bundles ?", 'options'=>['Oui >100 Mo', 'APK release ~25-30 Mo, AAB Play Store optimise par device (~15-20 Mo telecharge). Tree-shaking Dart elimine le code non utilise', 'Inconnu', '5 Go'], 'answer'=>1, 'explanation'=>"APK release ~25-30 Mo (Flutter inclut son runtime). <strong>AAB Play Store</strong> est decoupe par architecture device, telecharge final ~15-20 Mo. Tree-shaking Dart elimine le code mort."],
        ['chapter'=>0, 'question'=>"Avez-vous prevu un mode hors-ligne (offline) ?", 'options'=>['Oui complet', 'Non en V1. Limites : auth Sanctum requiert reseau, messages live impossible offline. Plan V2 : lecture cache des publications recentes via shared_preferences/sqflite', 'En 2030', 'Pas applicable'], 'answer'=>1, 'explanation'=>"Honnete : <strong>pas en V1</strong> (auth + messagerie requierent reseau). En V2 : cache lecture pubs recentes via <code>sqflite</code>, envoi de messages en file d'attente locale, sync au retour reseau."],
    ];
@endphp

@section('styles')
    @include('qcm._styles', ['config' => $config])
@endsection

@section('content')
    @include('qcm._engine', ['config' => $config, 'chapters' => $chapters, 'allQuestions' => $allQuestions])
@endsection
